model:
  arch: pretrain
  load_finetuned: False

  pretrained: "captioning.pth" # "/root/Downloads/trained_from_scratch/checkpoint_9.pth" #
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "float" # "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
